export const DISASTER_TYPES = [
  'Flood',
  'Fire',
  'Landslide',
  'Cyclone',
  'Earthquake',
  'Heavy Rainfall',
  'Thunderstorm',
  'Heatwave',
  'Strong Wind',
  'Other',
]

export const SEVERITY_LEVELS = ['Low', 'Medium', 'High', 'Critical']

export const VERIFICATION_STATUS = ['Pending', 'Verified', 'Rejected']

export const SEVERITY_COLORS = {
  Low: '#16a34a',
  Medium: '#eab308',
  High: '#ea580c',
  Critical: '#dc2626',
}

export const SEVERITY_BG = {
  Low: '#dcfce7',
  Medium: '#fef9c3',
  High: '#fed7aa',
  Critical: '#fee2e2',
}

export const STATUS_COLORS = {
  Pending: { bg: '#fef3c7', text: '#92400e' },
  Verified: { bg: '#dcfce7', text: '#166534' },
  Rejected: { bg: '#fee2e2', text: '#991b1b' },
}

export const DISASTER_ICON_COLORS = {
  Flood: '#0369a1',
  Fire: '#dc2626',
  Landslide: '#a16207',
  Cyclone: '#7c3aed',
  Earthquake: '#b45309',
  'Heavy Rainfall': '#0284c7',
  Thunderstorm: '#6d28d9',
  Heatwave: '#ea580c',
  'Strong Wind': '#0891b2',
  Other: '#6b7280',
}

// Fallback sample data used when the backend is not reachable.
// This ensures the UI is still demonstrable.
export const FALLBACK_INCIDENTS = [
  {
    incidentId: 'INC-1001',
    disasterType: 'Flood',
    description: 'Heavy rainfall has flooded roads near Pune station. Water entering shops and homes.',
    location: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    severity: 'High',
    confidence: 82,
    sources: ['Citizen', 'Weather API', 'News'],
    supportingReports: 3,
    status: 'Pending',
    aiAnalysis: { detectedType: 'Flood', extractedLocation: 'Pune', severityAssessment: 'High', confidenceScore: 85 },
    evidence: [
      { source: 'Citizen', description: 'Heavy rainfall has flooded roads near Pune station.', url: '' },
      { source: 'Weather API', description: 'Heavy rainfall warning for Pune district.', url: '' },
      { source: 'News', description: 'Flooding in Pune city center causes traffic disruption.', url: '' },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1002',
    disasterType: 'Fire',
    description: 'Massive fire broke out in a factory in Mumbai industrial area. Thick smoke visible.',
    location: 'Mumbai',
    latitude: 19.076,
    longitude: 72.8777,
    severity: 'Critical',
    confidence: 78,
    sources: ['Citizen', 'News'],
    supportingReports: 2,
    status: 'Pending',
    aiAnalysis: { detectedType: 'Fire', extractedLocation: 'Mumbai', severityAssessment: 'Critical', confidenceScore: 90 },
    evidence: [
      { source: 'Citizen', description: 'Massive fire broke out in a factory in Mumbai.', url: '' },
      { source: 'News', description: 'Major fire in Mumbai factory. Firefighters on scene.', url: '' },
    ],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1003',
    disasterType: 'Landslide',
    description: 'Landslide warning issued for Chamoli district. Hill slopes unstable after rainfall.',
    location: 'Chamoli',
    latitude: 30.4106,
    longitude: 79.3239,
    severity: 'High',
    confidence: 88,
    sources: ['Government Alert', 'Citizen'],
    supportingReports: 2,
    status: 'Verified',
    aiAnalysis: { detectedType: 'Landslide', extractedLocation: 'Chamoli', severityAssessment: 'High', confidenceScore: 85 },
    evidence: [
      { source: 'Government Alert', description: 'Landslide warning issued for Chamoli district.', url: '' },
      { source: 'Citizen', description: 'Landslide near Chamoli blocking highway.', url: '' },
    ],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1004',
    disasterType: 'Cyclone',
    description: 'Cyclone approaching Chennai coast. Wind speeds 120 km/h expected to make landfall.',
    location: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    severity: 'Critical',
    confidence: 92,
    sources: ['Weather API', 'Government Alert'],
    supportingReports: 2,
    status: 'Verified',
    aiAnalysis: { detectedType: 'Cyclone', extractedLocation: 'Chennai', severityAssessment: 'Critical', confidenceScore: 90 },
    evidence: [
      { source: 'Weather API', description: 'Cyclone approaching Chennai coast.', url: '' },
      { source: 'Government Alert', description: 'Cyclone alert for Tamil Nadu coast.', url: '' },
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1005',
    disasterType: 'Earthquake',
    description: 'Earthquake tremors felt in Delhi NCR. Buildings shaking for several seconds.',
    location: 'Delhi',
    latitude: 28.7041,
    longitude: 77.1025,
    severity: 'Medium',
    confidence: 72,
    sources: ['Citizen', 'Public Report'],
    supportingReports: 2,
    status: 'Pending',
    aiAnalysis: { detectedType: 'Earthquake', extractedLocation: 'Delhi', severityAssessment: 'Medium', confidenceScore: 80 },
    evidence: [
      { source: 'Citizen', description: 'Earthquake tremors felt in Delhi NCR.', url: '' },
      { source: 'Public Report', description: 'Earthquake felt across Delhi.', url: '' },
    ],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1006',
    disasterType: 'Heatwave',
    description: 'Heatwave conditions in Nagpur. Temperature 45 degrees. Extreme heat warning.',
    location: 'Nagpur',
    latitude: 21.1458,
    longitude: 79.0882,
    severity: 'High',
    confidence: 80,
    sources: ['Weather API'],
    supportingReports: 1,
    status: 'Verified',
    aiAnalysis: { detectedType: 'Heatwave', extractedLocation: 'Nagpur', severityAssessment: 'High', confidenceScore: 85 },
    evidence: [
      { source: 'Weather API', description: 'Heatwave conditions in Nagpur.', url: '' },
    ],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1007',
    disasterType: 'Landslide',
    description: 'Severe landslide in Wayanad, Kerala. Rescue operations underway. Multiple villages affected.',
    location: 'Wayanad',
    latitude: 11.6854,
    longitude: 76.132,
    severity: 'Critical',
    confidence: 90,
    sources: ['Government Alert', 'News'],
    supportingReports: 2,
    status: 'Verified',
    aiAnalysis: { detectedType: 'Landslide', extractedLocation: 'Wayanad', severityAssessment: 'Critical', confidenceScore: 90 },
    evidence: [
      { source: 'Government Alert', description: 'Landslide in Wayanad, Kerala.', url: '' },
      { source: 'News', description: 'Severe landslide in Wayanad. Casualties reported.', url: '' },
    ],
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    incidentId: 'INC-1008',
    disasterType: 'Thunderstorm',
    description: 'Thunderstorm with lightning in Kolkata. Heavy winds and rain.',
    location: 'Kolkata',
    latitude: 22.5726,
    longitude: 88.3639,
    severity: 'Medium',
    confidence: 65,
    sources: ['Citizen'],
    supportingReports: 1,
    status: 'Rejected',
    aiAnalysis: { detectedType: 'Thunderstorm', extractedLocation: 'Kolkata', severityAssessment: 'Medium', confidenceScore: 70 },
    evidence: [
      { source: 'Citizen', description: 'Thunderstorm with lightning in Kolkata.', url: '' },
    ],
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
]
