// Sample seed data for the prototype so the dashboard is not empty after deployment.
// This data represents mock citizen reports, weather alerts, news, and government alerts.

export const SEED_REPORTS = [
  {
    reportId: 'RPT-001',
    source: 'Citizen',
    description: 'Heavy rainfall has flooded roads near Pune station. Water entering shops and homes.',
    location: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    disasterType: 'Flood',
    severity: 'High',
    imageUrl: '',
    reporterName: 'Rajesh Kumar',
  },
  {
    reportId: 'RPT-002',
    source: 'Weather API',
    description: 'Heavy rainfall warning issued for Pune district. 120mm rainfall recorded in 3 hours.',
    location: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    disasterType: 'Heavy Rainfall',
    severity: 'High',
    imageUrl: '',
  },
  {
    reportId: 'RPT-003',
    source: 'News',
    description: 'Flooding in Pune city center causes traffic disruption. Multiple areas affected.',
    location: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    disasterType: 'Flood',
    severity: 'High',
    imageUrl: '',
  },
  {
    reportId: 'RPT-004',
    source: 'Citizen',
    description: 'Massive fire broke out in a factory in Mumbai industrial area. Thick smoke visible.',
    location: 'Mumbai',
    latitude: 19.076,
    longitude: 72.8777,
    disasterType: 'Fire',
    severity: 'Critical',
    imageUrl: '',
    reporterName: 'Sunita Sharma',
  },
  {
    reportId: 'RPT-005',
    source: 'News',
    description: 'Major fire in Mumbai factory. Firefighters on scene. Several injuries reported.',
    location: 'Mumbai',
    latitude: 19.076,
    longitude: 72.8777,
    disasterType: 'Fire',
    severity: 'Critical',
    imageUrl: '',
  },
  {
    reportId: 'RPT-006',
    source: 'Government Alert',
    description: 'Landslide warning issued for Chamoli district. Hill slopes unstable after rainfall.',
    location: 'Chamoli',
    latitude: 30.4106,
    longitude: 79.3239,
    disasterType: 'Landslide',
    severity: 'High',
    imageUrl: '',
  },
  {
    reportId: 'RPT-007',
    source: 'Citizen',
    description: 'Landslide near Chamoli blocking highway. Rocks and debris on road.',
    location: 'Chamoli',
    latitude: 30.4106,
    longitude: 79.3239,
    disasterType: 'Landslide',
    severity: 'High',
    imageUrl: '',
    reporterName: 'Anil Rana',
  },
  {
    reportId: 'RPT-008',
    source: 'Weather API',
    description: 'Cyclone approaching Chennai coast. Wind speeds 120 km/h expected to make landfall.',
    location: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    disasterType: 'Cyclone',
    severity: 'Critical',
    imageUrl: '',
  },
  {
    reportId: 'RPT-009',
    source: 'Government Alert',
    description: 'Cyclone alert for Tamil Nadu coast. Evacuation orders issued for coastal Chennai.',
    location: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    disasterType: 'Cyclone',
    severity: 'Critical',
    imageUrl: '',
  },
  {
    reportId: 'RPT-010',
    source: 'Citizen',
    description: 'Earthquake tremors felt in Delhi NCR. Buildings shaking for several seconds.',
    location: 'Delhi',
    latitude: 28.7041,
    longitude: 77.1025,
    disasterType: 'Earthquake',
    severity: 'Medium',
    imageUrl: '',
    reporterName: 'Priya Gupta',
  },
  {
    reportId: 'RPT-011',
    source: 'Public Report',
    description: 'Earthquake felt across Delhi. People rushing out of buildings.',
    location: 'Delhi',
    latitude: 28.7041,
    longitude: 77.1025,
    disasterType: 'Earthquake',
    severity: 'Medium',
    imageUrl: '',
  },
  {
    reportId: 'RPT-012',
    source: 'Weather API',
    description: 'Heatwave conditions in Nagpur. Temperature 45 degrees. Extreme heat warning.',
    location: 'Nagpur',
    latitude: 21.1458,
    longitude: 79.0882,
    disasterType: 'Heatwave',
    severity: 'High',
    imageUrl: '',
  },
  {
    reportId: 'RPT-013',
    source: 'Citizen',
    description: 'Thunderstorm with lightning in Kolkata. Heavy winds and rain.',
    location: 'Kolkata',
    latitude: 22.5726,
    longitude: 88.3639,
    disasterType: 'Thunderstorm',
    severity: 'Medium',
    imageUrl: '',
    reporterName: 'Soumitra Das',
  },
  {
    reportId: 'RPT-014',
    source: 'News',
    description: 'Strong winds damage structures in Jaipur. Trees uprooted in several areas.',
    location: 'Jaipur',
    latitude: 26.9124,
    longitude: 75.7873,
    disasterType: 'Strong Wind',
    severity: 'Medium',
    imageUrl: '',
  },
  {
    reportId: 'RPT-015',
    source: 'Citizen',
    description: 'Flooding in low lying areas of Guwahati after continuous rain.',
    location: 'Guwahati',
    latitude: 26.1445,
    longitude: 91.7362,
    disasterType: 'Flood',
    severity: 'Medium',
    imageUrl: '',
    reporterName: 'Bhola Nath',
  },
  {
    reportId: 'RPT-016',
    source: 'Government Alert',
    description: 'Landslide in Wayanad, Kerala. Rescue operations underway. Multiple villages affected.',
    location: 'Wayanad',
    latitude: 11.6854,
    longitude: 76.132,
    disasterType: 'Landslide',
    severity: 'Critical',
    imageUrl: '',
  },
  {
    reportId: 'RPT-017',
    source: 'News',
    description: 'Severe landslide in Wayanad. Casualties reported. Army called in for rescue.',
    location: 'Wayanad',
    latitude: 11.6854,
    longitude: 76.132,
    disasterType: 'Landslide',
    severity: 'Critical',
    imageUrl: '',
  },
  {
    reportId: 'RPT-018',
    source: 'Citizen',
    description: 'Fire in forest area near Shimla. Spreading quickly due to dry conditions.',
    location: 'Shimla',
    latitude: 31.1048,
    longitude: 77.1734,
    disasterType: 'Fire',
    severity: 'High',
    imageUrl: '',
    reporterName: 'Vikram Thakur',
  },
]
